token:
  expiration_time: 864000000
  secret: '{cipher}AQCXXP7PLnKntXPKCfkFDA1RS9jazt0KS+HYAX2o0RWxXxv1VD8g1tVBl3cH4firmy3yu1xWjLrlvukAvmNqw3FVzqqeBcGd9VutzUsXZ54QpdTWaP9OwBqCdFtXgfwDXf90ArgRHU8RDoYyfqdx9c+oVaOSzjEMgp3Y+sMHAmZMRntssWOD2HNfZf6eUVA9WOHhZjntZHMRHbPJFkH9RrSoC5tsqA7DNTBd4MtMZeqFVwpbGIYd1ssr+9Rzp9m3TovKETh3FDHJwMbWhizFTW/bt9m2xS+xDIdono4SEi70FZrL2kOro49dDYnruoxB0FQ+FB5w0hj2Uwp4A0vX2gdzsc1LUnoJWrH4csBgrqzH1i9y4pSsD12VEduf0+JBunJm64LwExa2af+Dvr3Rynj4'

server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scloud?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: '{cipher}AQCtIl4360iEjr5TXPg/oawdGDO5EAFC9thfKB/jtBuwWXBziNy0flBzJ2qkMgCOyawpZ21aOwygXvXMKz3/uLC2RHMfFrV+o1HMwRElxO7jSsjPkFkEsdMkoK7F7GeATCpYrA6ecyw1EFXO0iHCf7M2NmXnroWaVpS1J9twrLJW6azumeMTv4l3eatugTGGO+rmqF95RaNr0VUh360SVMEfPQgabJ2myAKGa9EBK8GvzHH/dWf6UP8sTALKxonfv68/j4YiXq/d+++B+IZ6vouNY1ZwwWiBWotTyZXhUJk5p+x81gOT/+ofMrnnXoNDx70RYeGdQf6k9Zi9XH9hGALVQ+LAJTdJ+wUQ8Nu6scCg9qtXgjyqylTefyM4BOYXbRU='
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka