token:
  expiration_time: 864000000
  secret: '{cipher}AQBvaumbYOGOA81pTPs2STrd7KtZ2vX0R5+v8qPcNVZ0PbCDiRjWdQZbIYYOyhEx8SiXv6SfB3MydzeqGVrFrB8K/S9ZQj9/wDbIjvjBNyTqdMJq1Nt57zaJWwF/+z2NNOXCaWPhIPuS+DSvMUwWGgNaTkK33EJYRFCS42SZng4ek0b9nTtAYupxHk5dw8NTU4xa/4gkX3bNZjxCVJ98X5Md3WHMEctq77ydXWSW5DGflaBbPVwc88gMVszSdwV2AkjDUtNJwTup3eoLt122VFX8jR6YZQK4E3DzepCyTN92LcF52kTZH8rh8Gg6ZH2jxgiDHIvqcBATnj/aqc13mD6IAeR+HMPZl+XnvmBLS+TTxi77mWzUnfHI9MH6BbQLczaz4QtJhA8dvGMWmdnUlFOV'

gateway:
  ip: 127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scloud?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: '{cipher}AQBR8lDFn8XBExGaSipAEAufQGkfiV/LTzzCNOIQEWeGNq86N/G+RMS2kppqtdk16vpxNMf+t8OO0VaPD80ryphnW6sVHp4bu0n9w94wx2DBLibKFEDquk5o8MFYV/UA6CJNcBLXuHqVJYGjXZg0Q6teg65Sd4hlkTNGjj8083AYmppgUmGLtiEaKdaNpqkuNGUSfPOdacJ9B82P3JuooMvei6bBOC6Ruq7/kdom5Lpgju4HBvUWSpmo5qa9/oxiBF+aJ43ewfXf+HatUXOLoLq9A7oMuO4FdjsHsJedPzC3gVpI85tKl215C+9c+NN9pBeswQGSk5SmVQ++PtyS9cjGECvgYjx1AYWcjkUJyrYEK9dKlZssWZcz5vZxJ1rkw7I='
  jpa:
    hibernate:
      ddl-auto: create